apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
spec:
  replicas: 4  
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: prakashvntt/boardgame:latest
        ports:
        - containerPort: 8080
<<<<<<< HEAD
      imagePullSecrets:
      - name: secrets
=======
>>>>>>> 61956e8ef8c762270492f6c0fe3b411d02af3e5f
