apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boardgame-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: prakashvntt/boardgame:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
