apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAg
ICJ1c2VybmFtZSI6ICJwcmFrYXNodm50dCIsCiAgICAgICJwYXNzd29yZCI6ICJDb21tdW5pY2F0
aW9uQDEyMzc4OSIsCiAgICAgICJlbWFpbCI6ICJwcmFrYXNoMTEudkBudHRkYXRhLmNvbSIKICAg
IH0KICB9Cn0K
