apiVersion: v1
kind: Service
metadata:
  name: boardgame
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 8080  # Port your application listens on inside the pods
      nodePort: 31002
  type: NodePort
